name: Claude Code Action (With Fix - Would Succeed)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review-success:
    runs-on: ubuntu-latest
    name: Claude Review (Shows Success with Fix)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Generate a GitHub App token with write permissions
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CLAUDE_GITHUB_APP_ID }}
          private-key: ${{ secrets.CLAUDE_GITHUB_PRIVATE_KEY }}
      
      # This would succeed with the proposed fix from PR #388
      # The trusted_bots parameter allows Dependabot to bypass actor permission checks
      - name: Claude Code Review (With Fix)
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ steps.app-token.outputs.token }}
          # This parameter is proposed in PR #388 - not yet available
          # When implemented, it would allow this workflow to succeed
          # trusted_bots: |
          #   dependabot[bot]